---
rvm: 2.2

sudo: required

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

install: echo "skip bundle install"

services: docker

env:
  matrix:
  - INSTANCE=service50-multi-centos-5
  - INSTANCE=service55-multi-centos-5
  - INSTANCE=service55-multi-centos-6
  - INSTANCE=service55-multi-centos-7
  - INSTANCE=service55-multi-ubuntu-1204
  - INSTANCE=service55-multi-ubuntu-1404
  - INSTANCE=service56-multi-centos-5
  - INSTANCE=service56-multi-centos-6
  - INSTANCE=service56-multi-centos-7
  - INSTANCE=service56-multi-fedora-21
  - INSTANCE=service56-multi-ubuntu-1404
  - INSTANCE=service56-multi-ubuntu-1504
  - INSTANCE=service57-multi-centos-5
  - INSTANCE=service57-multi-centos-6
  - INSTANCE=service57-multi-centos-7
  - INSTANCE=service57-multi-fedora-21
  fast_finish: true

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
  - /opt/chefdk/embedded/bin/chef --version
  # - /opt/chefdk/embedded/bin/rubocop --version
  # - /opt/chefdk/embedded/bin/rubocop
  # - /opt/chefdk/embedded/bin/foodcritic --version
  # - /opt/chefdk/embedded/bin/foodcritic . --exclude spec
  # - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log
