---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@5.0.8
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: "lint-unit"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        suite:
          - "client-install-80"
          - "client-install-84"
          - "smoke80"
          - "smoke84"
          - "resources-80"
          - "resources-84"
        os:
          - "almalinux-8"
          - "almalinux-9"
          - "centos-stream-9"
          - "debian-12"
          - "fedora-latest"
          - "rockylinux-8"
          - "rockylinux-9"
          - "ubuntu-2004"
          - "ubuntu-2204"
          - "ubuntu-2404"
        exclude:
          # MySQL 8.4 not available on older platforms
          - os: almalinux-8
            suite: client-install-84
          - os: almalinux-8
            suite: smoke84
          - os: almalinux-8
            suite: resources-84
          - os: rockylinux-8
            suite: client-install-84
          - os: rockylinux-8
            suite: smoke84
          - os: rockylinux-8
            suite: resources-84
          - os: ubuntu-2004
            suite: client-install-84
          - os: ubuntu-2004
            suite: smoke84
          - os: ubuntu-2004
            suite: resources-84
          - os: ubuntu-2204
            suite: client-install-84
          - os: ubuntu-2204
            suite: smoke84
          - os: ubuntu-2204
            suite: resources-84
          - os: debian-12
            suite: client-install-84
          - os: debian-12
            suite: smoke84
          - os: debian-12
            suite: resources-84
          - os: fedora-latest
            suite: client-install-84
          - os: fedora-latest
            suite: smoke84
          - os: fedora-latest
            suite: resources-84
          - os: centos-stream-9
            suite: client-install-84
          - os: centos-stream-9
            suite: smoke84
          - os: centos-stream-9
            suite: resources-84
          # MySQL 8.4 not available on Ubuntu 24.04 (uses 8.0)
          - os: ubuntu-2404
            suite: client-install-84
          - os: ubuntu-2404
            suite: smoke84
          - os: ubuntu-2404
            suite: resources-84
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install Chef
        uses: actionshub/chef-install@3.0.1
      # https://github.com/actions/virtual-environments/issues/181#issuecomment-610874237
      - name: Disable apparmor for mysqld
        run: |
          set -x
          sudo apt-get -y remove mysql-server --purge
          sudo apt-get -y install apparmor-profiles
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: Dokken
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
      - name: Print debug output on failure
        if: failure()
        run: |
          set -x
          sudo journalctl -l --since today
          sudo docker version
          sudo docker info
          KITCHEN_LOCAL_YAML=kitchen.dokken.yml /usr/bin/kitchen exec ${{ matrix.suite }}-${{ matrix.os }} -c "journalctl -l"
